name = "fightnight"
compatibility_date = "2026-05-22"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "fightnight"
database_id = "cf7a0050-4d76-4a31-b344-2fbc380dfdb0"
